### ISSUE TITLE
run.sh issues

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/dv-fuse-integration-demo#2]
The run.sh is confusing to me...  readme mentions that something 'might' be added to the run.sh and this is the only demo available with a run.sh.

Suggest removing it.

**Comment by eschabell** [comment]
Pushed a PR to fix this issue.

**Comment by kpeeples** [comment]
I am putting these files back.  Eric if you have questions with this demo then let me know.  We will be using run.sh to be running the demo after setting it up.

**Comment by kpeeples** [comment]
Cojan we will keep the readme and run.sh as we discussed.

**Comment by kpeeples** [comment]
The integration and multiproduct demos will contain a run.sh to help run the demos in addition to the init.sh which sets up the environment.
