### ISSUE TITLE
DV needs installer update 6.1.0

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/dv-fuse-integration-demo#6]
Needs to update to: jboss-dv-installer-6.1.0.Beta-redhat-1.jar

**Comment by kpeeples** [comment]
If anyone has time to upgrade to DV 6.1 Beta and Fuse 6.2 Beta then that would be good otherwise I will update on the following 2 releases:
1. DV 6.1 GA
2. Fuse 6.2 GA (update for Olingo use case)

**Comment by kpeeples** [comment]
We should be able to upgrade to:
Fuse 6.2 GA
DV 6.2 GA

**Comment by eschabell** [comment]
It already is up to Fuse 6.2, just need DV to catch up, got an ask this week after new releases came out.

**Comment by kpeeples** [comment]
Verified the release number was GA which is jboss-fuse-full-6.2.0.redhat-133.zip on the customer support portal and jboss.org.
